name: amr-env
channels:
    - defaults
    - bioconda
    - conda-forge

dependencies:
    - bwa=0.7.17
    - samtools=1.9
    - bcftools=1.9
    - kma=1.1.7
    - staramr=0.7.2
    - pandas=0.25.1
    - scikit-learn=0.21.2
    - numpy=1.16.5
    - matplotlib=3.1.1
    - wget=3.2
